In [1]:
import numpy as np

In [2]:

# Input sentence (tokenized)
words = ["What", "are", "the", "symptoms", "of", "diabetes"]

# Step 1: Random embeddings for each word (for simplicity)
np.random.seed(0)
embeddings = np.random.rand(len(words), 4)  # 4-dimensional embeddings

In [3]:
# Step 2: Initialize Weight matrices (Wq, Wk, Wv)
Wq = np.random.rand(4, 4)
Wk = np.random.rand(4, 4)
Wv = np.random.rand(4, 4)

In [4]:
# Step 3: Compute Query, Key, Value
Q = np.dot(embeddings, Wq)
K = np.dot(embeddings, Wk)
V = np.dot(embeddings, Wv)

In [5]:
# Step 4: Compute Attention Scores
scores = np.dot(Q, K.T)

# Step 5: Scale scores
d_k = Q.shape[1]
scores = scores / np.sqrt(d_k)

In [6]:
# Step 6: Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / exp_x.sum(axis=1, keepdims=True)

attention_weights = softmax(scores)

# Step 7: Final output (Self-Attention result)
output = np.dot(attention_weights, V)

# Print results
print("Attention Weights:\n", attention_weights)
print("\nOutput:\n", output)

Attention Weights:
 [[0.15613313 0.14733286 0.18837221 0.07784161 0.17859356 0.25172663]
 [0.15385631 0.14383864 0.19405694 0.07189619 0.17312872 0.2632232 ]
 [0.15621729 0.14442858 0.18935584 0.07590575 0.17950171 0.25459083]
 [0.16242608 0.15649727 0.18144369 0.10382821 0.17974393 0.21606081]
 [0.15191587 0.14507351 0.19014811 0.06849637 0.17528916 0.26907698]
 [0.15143574 0.13813405 0.1956768  0.06269177 0.17613446 0.27592718]]

Output:
 [[1.19597058 0.509796   1.87645234 0.62074247]
 [1.20483512 0.51322278 1.88379266 0.62427468]
 [1.19789431 0.51076633 1.87902701 0.62161114]
 [1.1677596  0.49953651 1.8445781  0.60767295]
 [1.20826892 0.51379191 1.88876339 0.62630745]
 [1.21418479 0.5168282  1.89576543 0.62879477]]
